environment: 'development'

cors: true

linebot:
  channelAccessToken: 'Your channelAccessToken'
  channelSecret: 'Your channelSecret'

db:
  mysql:
    host: 'localhost'
    port: '3306'
    username: 'a'
    password: '123456'
    database: 'meeting_manage'
  sqlite:
    database: 'sqlite/database.sqlite'


jwt:
  secret: abcdefg