environment: 'development'

domain: http://localhost:5000

cors: true

linebot:
  channelAccessToken: 'SYw058uBS7X2lPdMrc23u0CwNG9f7bDejnV8tXG0d0z8knVye6IyzfE3SQ5rxEVSCHZRvW8aHeJuLjQRQ//g1JDirYCpJl3W7opiByF9TMq8RXNn9k1r/Xnm7Cn36W7R61uX/ojGAss85Yv+vlO31gdB04t89/1O/w1cDnyilFU='
  channelSecret: '6e5136636ed30c5ddb7f072621a90953'



db:
  mysql:
    host: 'localhost'
    port: '3306'
    username: 'a'
    password: 'a31813141'
    database: 'meeting_manage'
  mysql_railway:
    host: 'containers-us-west-137.railway.app'
    port: '5510'
    username: 'a'
    password: 'a31813141'
    database: 'meeting_manage'
  sqlite:
    database: 'sqlite/database.sqlite'


jwt:
  secret: abcdefg